- name: "Instalando dependências"
  apt: name={{ item }} state=present
  with_items:
    - python-virtualenv
    - python-pip
    - libpq-dev 
    - python-dev
    - python-setuptools
    - ca-certificates
    - curl
    - apt-transport-https
    - software-properties-common
    - vim
