- name: "Adicionando o PPA do node.js"
  shell: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash 

- name: "Instalando nodejs"
  apt: name={{ item }} state=present
  with_items:
    - nodejs


 

