- name: "Adicionando GPG microsoft.gpg"
  shell: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg

- name: "Instalando a chave"
  shell: sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg

- name: "Adicionando repositorio do vscode"
  shell: sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

- name: "Instalando o vscode"
  shell: sudo apt update && sudo apt install code


    
