- name: "Removendo versões anteriores do eclipse"
  shell: rm -Rf /opt/eclipse/ && rm -Rf /usr/share/applications/eclipse.desktop

- name: "Baixando e Extraindo o eclipse para /opt/"
  unarchive:
    src: http://eclipse.c3sl.ufpr.br/technology/epp/downloads/release/2019-06/R/eclipse-jee-2019-06-R-linux-gtk-x86_64.tar.gz
    dest: /opt/
    remote_src: yes

- name: "Baixando icone do eclipse"
  get_url:
    url: https://dl2.macupdate.com/images/icons128/11662.png
    dest: /opt/eclipse/eclipse.png

- name: "Criando um lançador do eclipse no desktop"
  shell: touch /home/{{ user }}/'Área de Trabalho'/eclipse.desktop && chmod +x  /home/{{ user }}/'Área de Trabalho'/eclipse.desktop && echo "[Desktop Entry]\nName=eclipse\nType=Application\nExec=/opt/eclipse/eclipse\nIcon=/opt/eclipse/eclipse.png" >> /home/{{ user }}/'Área de Trabalho'/eclipse.desktop
  
