- name: "Instalando dependências"
  apt: name={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: "Adicionando chave docker"
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - 

- name: "Adicionando repositório docker"
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    
- name: "Instalando docker"
  apt:
    name: docker-ce
    update_cache: yes

- name: "Adicionando docker-compose"
  shell: composeFile=/usr/local/bin/docker-compose && composeVersion=1.24.1 && sudo curl -L "https://github.com/docker/compose/releases/download/${composeVersion}/docker-compose-$(uname -s)-$(uname -m)" -o "${composeFile}" && sudo chmod +x "${composeFile}"
    
